# Generated by Django 5.2.8 on 2025-11-16 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del modelo')),
                ('version', models.CharField(max_length=20, verbose_name='Versión')),
                ('model_file', models.CharField(help_text='Ruta al archivo .h5 del modelo', max_length=255, verbose_name='Archivo del modelo')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Precisión')),
                ('loss', models.FloatField(blank=True, null=True, verbose_name='Pérdida')),
                ('val_accuracy', models.FloatField(blank=True, null=True, verbose_name='Precisión de validación')),
                ('val_loss', models.FloatField(blank=True, null=True, verbose_name='Pérdida de validación')),
                ('training_samples', models.IntegerField(default=0, verbose_name='Muestras de entrenamiento')),
                ('epochs_trained', models.IntegerField(default=0, verbose_name='Épocas entrenadas')),
                ('architecture', models.TextField(blank=True, help_text='Descripción de la arquitectura del modelo', verbose_name='Arquitectura')),
                ('is_active', models.BooleanField(default=False, help_text='Indica si este es el modelo en uso actualmente', verbose_name='Modelo activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('trained_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrenamiento')),
            ],
            options={
                'verbose_name': 'Modelo de reconocimiento facial',
                'verbose_name_plural': 'Modelos de reconocimiento facial',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='face_images/', verbose_name='Imagen facial')),
                ('embedding', models.JSONField(blank=True, help_text='Vector de características extraído de la imagen', null=True, verbose_name='Embedding facial')),
                ('is_valid', models.BooleanField(default=True, help_text='Indica si la imagen es válida para entrenamiento', verbose_name='Es válida')),
                ('quality_score', models.FloatField(blank=True, help_text='Puntuación de calidad de la imagen detectada', null=True, verbose_name='Score de calidad')),
                ('face_detected', models.BooleanField(default=False, help_text='Indica si se detectó un rostro en la imagen', verbose_name='Rostro detectado')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_images', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Imagen facial',
                'verbose_name_plural': 'Imágenes faciales',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
