# Generated by Django 5.2.8 on 2025-11-16 02:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Nombre de usuario')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superusuario')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
                ('face_registered', models.BooleanField(default=False, verbose_name='Rostro registrado')),
                ('face_embedding', models.JSONField(blank=True, help_text='Vector de características del rostro', null=True, verbose_name='Embedding facial')),
                ('face_images_count', models.IntegerField(default=0, verbose_name='Número de imágenes faciales')),
                ('voice_registered', models.BooleanField(default=False, verbose_name='Voz registrada')),
                ('voice_embedding', models.JSONField(blank=True, help_text='Vector de características de la voz', null=True, verbose_name='Embedding de voz')),
                ('voice_samples_count', models.IntegerField(default=0, verbose_name='Número de muestras de voz')),
                ('multimodal_registered', models.BooleanField(default=False, verbose_name='Autenticación multimodal completa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='AuthenticationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_attempted', models.EmailField(max_length=254, verbose_name='Email intentado')),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('failed_face', 'Fallo en reconocimiento facial'), ('failed_voice', 'Fallo en reconocimiento de voz'), ('failed_both', 'Fallo en ambos'), ('failed_user', 'Usuario no encontrado')], max_length=20, verbose_name='Estado')),
                ('face_confidence', models.FloatField(blank=True, null=True, verbose_name='Confianza facial')),
                ('voice_confidence', models.FloatField(blank=True, null=True, verbose_name='Confianza de voz')),
                ('combined_confidence', models.FloatField(blank=True, null=True, verbose_name='Confianza combinada')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Intento de autenticación',
                'verbose_name_plural': 'Intentos de autenticación',
                'ordering': ['-timestamp'],
            },
        ),
    ]
